parameters:
#    kristian_randall_portfolio.example.class: KristianRandall\Bundle\PortfolioBundle\Example

services:
#    kristian_randall_portfolio.example:
#        class: %kristian_randall_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
