<?php

namespace Randak\Personal\PortfolioBundle\Model\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'project_category' table.
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Thu Dec 19 10:25:32 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.src.KristianRandall.Bundle.PortfolioBundle.Model.map
 */
class ProjectCategoryTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'src.KristianRandall.Bundle.PortfolioBundle.Model.map.ProjectCategoryTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('project_category');
        $this->setPhpName('ProjectCategory');
        $this->setClassname('KristianRandall\\Bundle\\PortfolioBundle\\Model\\ProjectCategory');
        $this->setPackage('src.KristianRandall.Bundle.PortfolioBundle.Model');
        $this->setUseIdGenerator(false);
        $this->setIsCrossRef(true);
        // columns
        $this->addForeignPrimaryKey('project_id', 'ProjectId', 'INTEGER' , 'project', 'id', true, null, null);
        $this->addForeignPrimaryKey('category_id', 'CategoryId', 'INTEGER' , 'category', 'id', true, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Project', 'KristianRandall\\Bundle\\PortfolioBundle\\Model\\Project', RelationMap::MANY_TO_ONE, array('project_id' => 'id', ), null, null);
        $this->addRelation('Category', 'KristianRandall\\Bundle\\PortfolioBundle\\Model\\Category', RelationMap::MANY_TO_ONE, array('category_id' => 'id', ), null, null);
    } // buildRelations()

} // ProjectCategoryTableMap
